version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./prisma:/usr/src/app/prisma
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:./prisma/dev.db
